### ISSUE TITLE
Logging Fails (Known Issue)

### ISSUE THREAD

**Issue by 5hawnknight** [reportportal/examples-scala#2]
More of a general question than repeating the known issue with logging with ScalaTest, is there a plan to resolving the issue?

**Comment by HardNorth** [comment]
There are always some plans. But I have 12 JVM agents with something like 20 features each, most of them still weren't implemented and there are many build issues with them. So currently I think I'll get some time to rewrite/fix scala agent not early than few years from now.

**Comment by 5hawnknight** [comment]
fair enough. thank you for the updated and your insight was helpful.
